### ISSUE TITLE
Tutorial for iOS and Android

### ISSUE THREAD

**Issue by atonamy** [Schr3da/godot-rust#1]
Did you able to run successfully Rust gdnative scripts on mobile platforms iOS and Android?
I managed to build it but not able to run it on Android or iOS.

Maybe you have some success in this to share?

**Comment by Schr3da** [comment]
Hey,
unfortunately I tried several ways but was unable to successfully run it on ios. It seems that godot has still some issues with gdnative script on non desktop platforms.

https://www.reddit.com/r/godot/comments/f3uzus/compiling_gdnative_for_mobile/

In addition I reached out to the community but didnt get much response :(

https://godotengine.org/qa/68675/gdnative-script-and-ios
https://godotengine.org/qa/67092/godot-engine-and-rust-programming-language

For compiling the gdnative script I followed the following description using clippy:

https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-06-rust-on-ios.html

Compiling was successful but it seems that the library are not properly loaded when running in Simulator or directly on the device.

**Comment by atonamy** [comment]
> Hey,
> unfortunately I tried several ways but was unable to successfully run it on ios. It seems that godot has still some issues with gdnative script on non desktop platforms.
> 
> https://www.reddit.com/r/godot/comments/f3uzus/compiling_gdnative_for_mobile/
> 
> In addition I reached out to the community but didnt get much response :(
> 
> https://godotengine.org/qa/68675/gdnative-script-and-ios
> https://godotengine.org/qa/67092/godot-engine-and-rust-programming-language
> 
> For compiling the gdnative script I followed the following description using clippy:
> 
> https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-06-rust-on-ios.html
> 
> Compiling was successful but it seems that the library are not properly loaded when running in Simulator or directly on the device.

Well I have a good news for you. I managed to run godot with gdnative rust on iOS (real device), but I have a problem to run on iOS simulator.

**Comment by Schr3da** [comment]
Nice i was actually seeing your post in the other repo :) great job!!!! 
I will close the issue and will share the link in addition
https://github.com/GodotNativeTools/godot-rust/issues/343

**Comment by atonamy** [comment]
> Nice i was actually seeing your post in the other repo :) great job!!!!
> I will close the issue and will share the link in addition
> [GodotNativeTools/godot-rust#343](https://github.com/GodotNativeTools/godot-rust/issues/343)

No problem. If you need any help with Android/iOS build let me know.
